parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        resolve_target_entities:
            App\Infrastructure\Machine\Collector\BasicDataCollectorInterface: App\DataSourceLayer\Infrastructure\Machine\Doctrine\Entity\BasicDataCollector
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            LearningMetadata:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DataSourceLayer/Infrastructure/LearningMetadata/Doctrine/Entity'
                prefix: 'App\DataSourceLayer\Infrastructure\LearningMetadata\Doctrine\Entity'
                alias: LearningMetadata

            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DataSourceLayer/Infrastructure/Security/Doctrine/Entity'
                prefix: 'App\DataSourceLayer\Infrastructure\Security\Doctrine\Entity'
                alias: Security

            Machine:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DataSourceLayer/Infrastructure/Machine/Doctrine/Entity'
                prefix: 'App\DataSourceLayer\Infrastructure\Machine\Doctrine\Entity'
                alias: Security
