jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    metadata:
        auto_detection: false
        directories:
            entire_application:
                path: '%kernel.root_dir%/../config/jms_serializer'

