app_index:
    path:     /
    controller: App\PresentationLayer\LearningMetadata\EntryPoint\StaticEntryPoint::getIndex
    methods: [GET]
    host: 33.33.33.10
    schemes: [http]
    requirements:
        _format: 'text/html'
