app_static:
    prefix: /
    resource: 'Static/'
    methods: [GET]
    host: 33.33.33.10
    schemes: [http]
    type: directory
    requirements:
        _format: 'text/html'

admin_main_import:
    prefix: /admin
    resource: 'Admin/main.yml'
    host: 33.33.33.10
    schemes: [http]

app_user:
    prefix: /api/v1/user
    resource: 'Security/'
    methods: [GET]
    host: 33.33.33.10
    schemes: [http]
    type: directory
    requirements:
        _format: 'application/json'

app_learning_metadata:
    prefix: /api/v1/learning-metadata
    resource: 'LearningMetadata/'
    host: 33.33.33.10
    schemes: [http]
    type: directory
    requirements:
        _format: 'application/json'
