App\PresentationLayer\Model\Locale:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int
        name:
            expose: true
            groups: [default]
            type: string