App\PresentationLayer\Model\Language:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int
        name:
            expose: true
            groups: [default]
            type: string

        showOnPage:
            expose: true
            groups: [default]
            type: bool
            serialized_name: showOnPage

        description:
            expose: true
            groups: [default]
            type: string

        image:
            expose: true
            groups: [default]
            type: App\PresentationLayer\Model\Image