App\LogicLayer\LearningMetadata\Domain\Language:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        locale:
            expose: true
            groups: [default]
            type: string

        showOnPage:
            expose: true
            groups: [default]
            type: bool
            serialized_name: showOnPage

        image:
            expose: true
            groups: [default]
            type: App\LogicLayer\LearningMetadata\Domain\Image

        description:
            expose: true
            groups: [default]
            type: string

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>