App\PresentationLayer\Model\Word\Translation:
    exlusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        locale:
            expose: true
            groups: [default]
            type: string

        valid:
            expose: true
            groups: [default]
            type: boolean