App\DataSourceLayer\Infrastructure\LearningMetadata\Doctrine\Entity\Locale:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        default:
            expose: true
            groups: [default]
            type: bool

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>