App\DataSourceLayer\Infrastructure\LearningMetadata\Doctrine\Entity\Word\Translation:
    exlusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        locale:
            expose: true
            groups: [default]
            type: string

        valid:
            expose: true
            groups: [default]
            type: boolean

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>