App\PresentationLayer\Model\Word\Image:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        relativePath:
            expose: true
            groups: [default]
            type: string