App\LogicLayer\Security\Domain\User:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        locale:
            expose: true
            groups: [default]
            type: App\LogicLayer\LearningMetadata\Domain\Locale

        name:
            expose: true
            groups: [default]
            type: string

        lastname:
            expose: true
            groups: [default]
            type: string

        username:
            expose: true
            groups: [default]
            type: string

        email:
            expose: true
            groups: [default]
            type: string

        password:
            expose: true
            groups: [default]
            type: string

        enabled:
            expose: true
            groups: [default]
            type: bool

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>