App\PresentationLayer\Infrastructure\Model\Lesson:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        locale:
            expose: true
            groups: [default]
            type: string

        temporaryText:
            expose: true
            groups: [default]
            type: string
            serialized_name: temporaryText

        language:
            expose: true
            groups: [default]
            type: App\PresentationLayer\Infrastructure\Model\Language