App\PresentationLayer\Infrastructure\Model\Lesson:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        internalName:
            expose: true
            groups: [default]
            type: string
            serialized_name: internalName

        locale:
            expose: true
            groups: [default]
            type: string

        lessonData:
            expose: true
            groups: [default]
            type: array<App\PresentationLayer\Infrastructure\Model\LessonData>
            serialized_name: lessonData

        language:
            expose: true
            groups: [default]
            type: App\PresentationLayer\Infrastructure\Model\Language