App\PresentationLayer\Model\Word\Word:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        type:
            expose: true
            groups: [default]
            type: string

        language:
            expose: true
            groups: [default]
            type: App\PresentationLayer\Model\Language

        description:
            expose: true
            groups: [default]
            type: string

        level:
            expose: true
            groups: [default]
            type: int

        pluralForm:
            expose: true
            groups: [default]
            type: string

        categories:
            expose: true
            groups: [default]
            type: array<App\PresentationLayer\Model\Category>

        translations:
            expose: true
            groups: [default]
            type: array<App\PresentationLayer\Model\Word\Translation>

        image:
            expose: true
            groups: [default]
            type: App\PresentationLayer\Model\Word\Image
