App\DataSourceLayer\Infrastructure\Doctrine\Entity\Word\Word:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        type:
            expose: true
            groups: [default]
            type: string

        language:
            expose: true
            groups: [default]
            type: App\DataSourceLayer\Infrastructure\Doctrine\Entity\Language

        description:
            expose: true
            groups: [default]
            type: string

        level:
            expose: true
            groups: [default]
            type: int

        pluralForm:
            expose: true
            groups: [default]
            type: string
            serialized_name: pluralForm

        translations:
            expose: true
            groups: [default]
            type: array<App\DataSourceLayer\Infrastructure\Doctrine\Entity\Word\Translation>

        image:
            expose: true
            groups: [default]
            type: App\DataSourceLayer\Infrastructure\Doctrine\Entity\Word\Image

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>