App\DataSourceLayer\Infrastructure\Security\Doctrine\Entity\User:
    exclusion_policy: all
    properties:
        id:
            exclude: false
            groups: [default]
            type: int

        name:
            exclude: false
            groups: [default]
            type: string

        lastname:
            exclude: false
            groups: [default]
            type: string

        username:
            exclude: false
            groups: [default]
            type: string

        email:
            exclude: false
            groups: [default]
            type: string

        password:
            exclude: false
            groups: [default]
            type: string

        enabled:
            exclude: false
            groups: [default]
            type: bool

        createdAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default]
            type: DateTime<'Y-m-d H:m:s'>