App\PresentationLayer\Model\Category:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default]
            type: int

        name:
            expose: true
            groups: [default]
            type: string

        locale:
            expose: true
            groups: [default]
            type: string