<?php

namespace App\Tests\Unit;

use Library\Http\Request\ResolvedRequest;
use Library\Validation\SymfonyValidatorFacade;
use Psr\Container\ContainerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ResolvedRequestTest extends WebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        static::createClient();
    }

    public function test_valid_resolved_request()
    {
        $validRequest = [
            'internal_type' => 'view',
            'name' => 'name',
            'data' => [
                'some_data' => [],
            ],
            'method' => 'get',
        ];

        /** @var SymfonyValidatorFacade $symfonyValidator */
        $symfonyValidator = static::$container->get('library.facade.symfony_validator');

        $resolvedRequest = new ResolvedRequest(
            $validRequest,
            $symfonyValidator
        );

        static::assertEquals($validRequest['method'], $resolvedRequest->getMethod());
        static::assertEquals($validRequest['name'], $resolvedRequest->getName());
        static::assertEquals($validRequest['internal_type'], $resolvedRequest->getInternalType());
    }
}