<?php

namespace App\Tests\Unit;

use Library\Http\Request\RequestDataModel;
use Library\Http\Request\ResolvedRequest;
use Library\Infrastructure\Helper\ModelValidator;
use Library\Infrastructure\Helper\SerializerWrapper;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ResolvedRequestTest extends WebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        static::createClient();
    }

    public function test_valid_resolved_request()
    {
        $validRequest = [
            'internal_type' => 'view',
            'name' => 'name',
            'data' => [
                'some_data' => [],
            ],
            'method' => 'get',
        ];

        /** @var RequestDataModel $requestDataModel */
        $requestDataModel = static::$container
            ->get(SerializerWrapper::class)
            ->deserialize($validRequest, RequestDataModel::class);

        $modelValidator = static::$container->get(ModelValidator::class);
        $modelValidator->validate($requestDataModel);

        $resolvedRequest = new ResolvedRequest(
            $requestDataModel,
            $modelValidator
        );

        static::assertEquals($validRequest['method'], $resolvedRequest->getMethod());
        static::assertEquals($validRequest['name'], $resolvedRequest->getName());
        static::assertEquals($validRequest['internal_type'], $resolvedRequest->getInternalType());
    }

    public function test_invalid_resolved_request()
    {
        $validRequest = [
            'internal_type' => 'view',
            'name' => 'name',
            'data' => [
                'some_data' => [],
            ],
            'method' => 'get',
        ];

        $requestKeys = array_keys($validRequest);

        $modelValidator = static::$container->get(ModelValidator::class);

        foreach ($requestKeys as $key) {
            $entersException = false;

            $previousValue = $validRequest[$key];
            $validRequest[$key] = '';

            try {
                /** @var RequestDataModel $requestDataModel */
                $requestDataModel = static::$container
                    ->get(SerializerWrapper::class)
                    ->getDeserializer()
                    ->create($validRequest, RequestDataModel::class);

                new ResolvedRequest(
                    $requestDataModel,
                    $modelValidator
                );

            } catch (\RuntimeException $e) {
                $entersException = true;

                $validRequest[$key] = $previousValue;
            }

            static::assertTrue($entersException);
        }
    }
}